#!/usr/bin/env bash
#MISE description="Compile dotfiles release"
#USAGE arg "<arch>" help="Target architecture" {
#USAGE   choices "amd64" "arm64"
#USAGE }

set -Eeuo pipefail

ARCH="${usage_arch:?}"
NAME="${PROJECT_NAME:?PROJECT_NAME is not defined}"
VERSION="${PROJECT_VERSION:?PROJECT_VERSION is not defined}"

OUT="./${NAME}_${VERSION}_${ARCH}"

rm -rf -- "$OUT"
mkdir -p \
    "$OUT/hypr" \
    "$OUT/quickshell/assets" \
    "$OUT/quickshell/scripts"

cp "./.installer/install.sh" "$OUT/install.sh"

cp -a "./hypr/." "$OUT/hypr/"

cp -a "./quickshell/." "$OUT/quickshell/"

cp \
    "./assets/fonts/Geist.ttf" \
    "./assets/fonts/Icons.json" \
    "./assets/fonts/Icons.ttf" \
    "./assets/images/popover-shadow.png" \
    "$OUT/quickshell/assets/"

cp "./bin/sun-times-$ARCH" \
    "$OUT/quickshell/scripts/sun-times"

cp "./bin/timezone-at-$ARCH" \
    "$OUT/quickshell/scripts/timezone-at"

cp \
    "./scripts/change-color-theme.sh" \
    "./scripts/change-timezone.sh" \
    "$OUT/quickshell/scripts/"

chmod +x \
    "$OUT/install.sh" \
    "$OUT/quickshell/scripts/sun-times" \
    "$OUT/quickshell/scripts/timezone-at" \
    "$OUT/quickshell/scripts/change-color-theme.sh" \
    "$OUT/quickshell/scripts/change-timezone.sh"

echo "Compiled in $OUT"